### ISSUE TITLE
Add display names to models

### ISSUE THREAD

**Issue by SoryRawyer** [openedx/aspects-dbt#12]
### Problem
The dbt models currently only have entity IDs. Superset dashboards should have the entity names, which are much more readable and would bring the dashboards in line with previous insights UX. This data currently lives in the `event_sink` schema in two tables: `course_blocks`, which has display names for entities like videos; and `course_overviews`, which contains the course name.

There are a couple different ways of approaching this problem and I'd love to get feedback before proceeding.

### Approaches
As I see it, there are two high-level approaches:
1. Create new views in dbt that include display names
2. Create virtual datasets in Superset that build off the existing dbt models and joins in display names

The key performance difference between these two approaches is that ClickHouse will not use primary keys for right-hand side tables in joins. This means that the following query will not do any filtering of the `course_blocks` table despite filtering on `org`, which is the first part of the primary key in `course_blocks`:
```sql
select
    b.location as video_name,
    count(*) as num_plays
from
    xapi.video_plays vp
    join event_sink.course_blocks b
        on vp.video_id = b.location
where
    vp.org = 'edX' and b.org = 'edX'
group by 1
```

This could become a problem if the right-hand side table is sufficiently large, as ClickHouse defaults to reading the entire right-hand side into memory (though ClickHouse has a setting where queries could adapt to use a slower, more memory-resilient join algorithm).

The following query, however, _will_ use the primary key in `course_blocks`:
```sql
with blocks as (
    select
        location,
        display_name
    from
        event_sink.course_blocks
    where org ='edX'
)
select
    b.display_name as video_name,
    count(*) as num_plays
from
    xapi.video_plays vp
    join blocks b
        on vp.video_id = b.location
where
    vp.org = 'edX'
group by 1
```

The advantage of Superset would be that we could use [SQL templates](https://superset.apache.org/docs/installation/sql-templating/) to use a version of the second query to power dashboards. Given a dashboard filter with the name `org`, the templated version would look similar to this:
```sql
with blocks as (
    select
        location,
        display_name
    from
        event_sink.course_blocks
    where
        -- where_in is provided by Superset. If we want to filter on the org 'edX', where_in
        -- converts the filter value to something like this: `('edX')` 
        org in {{ filter_values('org') | where_in }}
)
select
    b.display_name as video_name,
    count(*) as num_plays
from
    xapi.video_plays vp
    join blocks b
        on vp.video_id = b.location
where
    vp.org {{ filter_values('org') | where_in }}
group by 1
```

Given this information, I think the dbt approach is more appealing from a developer experience perspective while sacrificing performance. The Superset approach has a performance benefit but at the cost of added complexity by defining what is essentially another dbt model but outside of dbt.

**Comment by SoryRawyer** [comment]
At the moment, I'm inclined to favor the Superset option. While messier, I think it will be important to limit the data selected from the event_sink tables before joining, which I don't think is possible in ClickHouse right now.

**Comment by bmtcril** [comment]
Hmmm, yeah it's a weird constraint to have to work around. I'm not sure how rbac would work with the virtual dataset, but that would be worth knowing. I'm going to add this question and the permissions question to the thread with the clickhouse onboarding team to see what they say.

**Comment by SoryRawyer** [comment]
If we're using Superset for the permissions, I think we'd need to include any virtual datasets as well (but I don't think we'd have an issue getting virtual datasets to work with Superset's RBAC).
I haven't yet looked into ClickHouse's RBAC to be sure it would do the right thing, but I think it would still limit the queries to the underlying tables and restrict the returned data that way.

**Comment by bmtcril** [comment]
Hey @SoryRawyer would you consider this done now?

**Comment by SoryRawyer** [comment]
@bmtcril yes, I'd consider this done.
