### ISSUE TITLE
Models for video engagement reports

### ISSUE THREAD

**Issue by bmtcril** [openedx/aspects-dbt#3]
Reports being served by these models:

- Number of watches per video
- Average use of transcripts / closed captions per video

**Comment by SoryRawyer** [comment]
A couple questions to clarify the parameters of these reports:
1. Is it safe to assume that the "watchers per video" should be the same as the definition described in the "watched a video last week metric" section of the [engagement computation reference](https://edx.readthedocs.io/projects/edx-insights/en/latest/Reference.html#engagement-computations)? In other words, a count of `actor_id`s with at least one `played` event?
2. I'm interpreting the "use of transcripts/cc" metric as being a simple count of people who have enabled the transcript/closed captions at least once. Does that sound right, or should we add anything else to this report (like duration of transcript/cc usage, etc)?

**Comment by bmtcril** [comment]
@SoryRawyer I think that both of those assumptions are correct. I wouldn't add anything else to them at this point, we haven't had any requests for more information on those points yet.
