### ISSUE TITLE
Models for problem engagement

### ISSUE THREAD

**Issue by bmtcril** [openedx/aspects-dbt#4]
Reports pulling from these models:

- Problem submission counts
- Answer distributions per problem
- Problem difficulty

**Comment by SoryRawyer** [comment]
Are there any existing metrics that have helped instructors assess problem difficulty? I know we've talked about a metric like "number of attempts to first success", which seems like a good one. Is there anything else that's proven useful in the past?

**Comment by bmtcril** [comment]
I think that "attempts to first success" and "number of show hint / number of show answers per correct answer" can provide a good first pass for difficulty. I think it will give us a good jumping off point for discussions with instructors about what might be better.

**Comment by bmtcril** [comment]
1. It's possible for people to keep messing with problems, even after they're correct so they occasionally do. I think for difficulty of problem assessment attempts-to-first-success is still a better metric. We might want to measure "most recent state" for other things like learner progress, but I think that's out of scope for this batch.
2. That makes sense to me!
